name: Node.js CI

on:
  push:
    branches:
      - main
  # You can also trigger the workflow on tags, pull requests, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test # Optional, if you have tests
    - name: Deploy
      run: |
        # Your deployment commands here
        # Example for deployment to a server using SSH:
        scp -r ./dist username@server:/path/to/deploy
        ssh username@server 'cd /path/to/deploy && npm install --production && pm2 restart app'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # Add other secrets or environment variables as needed
